apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: onosqueuenetcfgs.bans.io
spec:
  group: bans.io
  names:
    kind: OnosQueueNetcfg
    listKind: OnosQueueNetcfgList
    plural: onosqueuenetcfgs
    singular: onosqueuenetcfg
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: OnosQueueNetcfg is the Schema for the onosqueuenetcfgs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OnosQueueNetcfgSpec defines the desired state of OnosQueueNetcfg
          properties:
            queueDevices:
              additionalProperties:
                description: Queues
                items:
                  description: Queue
                  properties:
                    port:
                      description: Port
                      type: integer
                    priority:
                      description: Priority
                      type: integer
                    qid:
                      description: Queue ID
                      type: integer
                    weight:
                      description: Weight
                      type: integer
                  required:
                  - port
                  - priority
                  - qid
                  - weight
                  type: object
                type: array
              description: Queue devices
              type: object
          required:
          - queueDevices
          type: object
        status:
          description: OnosQueueNetcfgStatus defines the observed state of OnosQueueNetcfg
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
