apiVersion: apps/v1
kind: Deployment
metadata:
  name: onos-bandwidth-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onos-bandwidth-operator
  template:
    metadata:
      labels:
        name: onos-bandwidth-operator
    spec:
      serviceAccountName: onos-bandwidth-operator
      containers:
        - name: onos-bandwidth-operator
          # Replace this with the built image name
          image: steven30801/onos-bandwidth-operator:bmv2-fabric
          command:
          - onos-bandwidth-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "onos-bandwidth-operator"
