apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onos.fullname" . }}
  labels:
    {{- include "onos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "onos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "onos.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "onos.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./bin/onos-service", "server", "debug"]
          stdin: true
          tty: true
          ports:
{{- range $key, $value := .Values.service }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
{{- end }}
          env:
            {{ toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
